{
 "title": "MySQL Backup",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mysql_s3_backup_successful,instance)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(mysql_s3_backup_duration_in_ms{instance=~\"$instance\"},database)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(mysql_s3_backup_duration_in_ms{instance=~\"$instance\",database=~\"$database\"},table)"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_s3_backup_successful{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last execution",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "mysql_s3_backup_start_timestamp{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (mysql_s3_backup_duration_in_ms{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data size",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (mysql_s3_backup_file_size_in_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database total duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (database) (mysql_s3_backup_duration_in_ms{instance=~\"$instance\",database=~\"$database\"})",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database total file size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (database) (mysql_s3_backup_file_size_in_bytes{instance=~\"$instance\",database=~\"$database\"})",
       "legendFormat": "{{database}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Datase & Table details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (database,table)(mysql_s3_backup_duration_in_ms{instance=~\"$instance\",database=~\"$database\",table=~\"$table\"})",
       "legendFormat": "{{database}} - {{table}}"
      }
     ]
    },
    {
     "title": "File size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by (database,table) (mysql_s3_backup_file_size_in_bytes{instance=~\"$instance\",database=~\"$database\",table=~\"$table\"})",
       "legendFormat": "{{database}} - {{table}}"
      }
     ]
    }
   ]
  }
 ]
}