# This configuration is used for the deployment and publish to docker
name: release

on:
  push:
    branches:
      # Runs only on push to the master branch
      - master

jobs:
  release:
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the git repository
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GPR_TOKEN }}
          fetch-depth: ''

      # Execute some necessary git commands to get more repository informations
      - name: post-checkout
        run: git fetch --prune --unshallow

      # Get the current project version from POM
      - name: get-project-version
        id: get_project_version
        uses: avides/actions-project-version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: version.txt
          only-return-version: true

      # Build and publish docker image
      - name: push-image
        env:
          PROJECT_VERSION: ${{ steps.get_project_version.outputs.version }}
        run: |
          docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:${PROJECT_VERSION} -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:latest .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:${PROJECT_VERSION}
          if [[ "$PROJECT_VERSION" != *"SNAPSHOT"* || "$PROJECT_VERSION" != *"RC"* ]]; then
            docker push ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:latest
          fi

      # Get last commit message for GitHub Release tag
      - name: setup-github-release
        id: setup_github_release
        env:
          PROJECT_VERSION: ${{ steps.get_project_version.outputs.version }}
        run: |
          echo ::set-output name=gitcommitmessage::$(git log --no-merges -1 --oneline)
          if [[ "$PROJECT_VERSION" == *"SNAPSHOT"* || "$PROJECT_VERSION" == *"RC"* ]]; then
            echo ::set-output name=isprerelease::true
          fi

      # Create and publish GitHub Release tag
      - name: github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
        with:
          tag_name: ${{ steps.get_project_version.outputs.version }}
          release_name: ${{ steps.get_project_version.outputs.version }}
          body: ${{ steps.setup_github_release.outputs.gitcommitmessage }}
          prerelease: ${{ steps.setup_github_release.outputs.isprerelease }}
