name: review
 
on:
  pull_request:
    types: [opened, synchronize]
 
jobs:
  review:
    timeout-minutes: 30
    runs-on: ubuntu-latest
 
    steps:
      - name: checkout
        uses: actions/checkout@v1
 
      - name: project-version-check
        id: project_version_check
        uses: avides/actions-project-version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: version.txt
          additional-files-to-check: README.md
 
      - name: build-image
        run: |
          export PROJECT_VERSION=${{ steps.project_version_check.outputs.version }}
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:${PROJECT_VERSION} -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:latest .
