name: review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GPR_TOKEN }}
          fetch-depth: ''

      - name: post-checkout
        run: git fetch --prune --unshallow

      - name: action-configuration-autoupdate
        id: actions_action_configuration_autoupdate
        uses: avides/actions-action-configuration-autoupdate@v1
        with:
          token: ${{ secrets.GPR_TOKEN }}
          actions-configuration-files: plain-docker-application/nightly.yml,plain-docker-application/release.yml,plain-docker-application/review.yml
          source-repository: ${{ secrets.ACTIONS_CONFIG_AUTOUPDATE_REPO }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: .github/workflows/*.yml
          commit_user_name: ${{ secrets.ACTIONS_CONFIG_AUTOUPDATE_USER }}
          commit_user_email: ${{ secrets.ACTIONS_CONFIG_AUTOUPDATE_EMAIL }}
          commit_author: ${{ secrets.ACTIONS_CONFIG_AUTOUPDATE_AUTHOR }}
          commit_message: Update GitHub Action configuration

      - name: action-configuration-updated
        if: ${{ steps.actions_action_configuration_autoupdate.outputs.updated }}
        run: exit 1;

      - name: project-version-check
        id: project_version_check
        uses: avides/actions-project-version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: version.txt

      - name: build-image
        env:
          PROJECT_VERSION: ${{ steps.project_version_check.outputs.version }}
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:${PROJECT_VERSION} -t ${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REPOSITORY}:latest .
